# Generated by Django 5.0.6 on 2024-07-05 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paytm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+$')]),
        ),
    ]
